#!/usr/bin/env python3
"""Generate the small browser-facing curriculum projection."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

from curriculum_yaml import CurriculumYAMLError, load


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "data" / "curriculum.yml"
OUTPUT = ROOT / "assets" / "curriculum-data.js"
HEADER = (
    "/* Generated from data/curriculum.yml by "
    "scripts/generate_curriculum_data.py.\n"
    " * Do not edit this file directly.\n"
    " */\n"
)


def _browser_payload(data: Any) -> dict[str, Any]:
    if not isinstance(data, dict):
        raise ValueError("curriculum root must be a mapping")
    version = data.get("version")
    domains = data.get("domains")
    modules = data.get("modules")
    if type(version) is not int:
        raise ValueError("curriculum version must be an integer")
    if not isinstance(domains, list):
        raise ValueError("curriculum domains must be a list")
    if not isinstance(modules, list):
        raise ValueError("curriculum modules must be a list")

    domain_projection: list[dict[str, Any]] = []
    for index, domain in enumerate(domains, start=1):
        if not isinstance(domain, dict):
            raise ValueError(f"domain entry {index} must be a mapping")
        domain_id = domain.get("id")
        order = domain.get("order")
        title = domain.get("title")
        guiding_question = domain.get("guiding_question")
        module_ids = domain.get("module_ids")
        if not isinstance(domain_id, str) or not domain_id:
            raise ValueError(f"domain entry {index} has an invalid id")
        if type(order) is not int:
            raise ValueError(f"{domain_id}: order must be an integer")
        if not isinstance(title, str) or not title.strip():
            raise ValueError(f"{domain_id}: title must be a non-empty string")
        if not isinstance(guiding_question, str) or not guiding_question.strip():
            raise ValueError(
                f"{domain_id}: guiding_question must be a non-empty string"
            )
        if (
            not isinstance(module_ids, list)
            or not module_ids
            or any(
                not isinstance(module_id, str) or not module_id
                for module_id in module_ids
            )
        ):
            raise ValueError(
                f"{domain_id}: module_ids must be a non-empty list of IDs"
            )
        domain_projection.append(
            {
                "id": domain_id,
                "order": order,
                "title": title,
                "guiding_question": guiding_question,
                "module_ids": list(module_ids),
            }
        )

    module_projection: list[dict[str, Any]] = []
    for index, module in enumerate(modules, start=1):
        if not isinstance(module, dict):
            raise ValueError(f"module entry {index} must be a mapping")
        module_id = module.get("id")
        order = module.get("order")
        display_code = module.get("display_code")
        title_el = module.get("title_el")
        domain_id = module.get("domain_id")
        available = module.get("available")
        status = module.get("status")
        lesson = module.get("lesson")
        if not isinstance(module_id, str) or not module_id:
            raise ValueError(f"module entry {index} has an invalid id")
        if type(order) is not int:
            raise ValueError(f"{module_id}: order must be an integer")
        if not isinstance(display_code, str) or not display_code:
            raise ValueError(
                f"{module_id}: display_code must be a non-empty string"
            )
        if not isinstance(title_el, str) or not title_el.strip():
            raise ValueError(f"{module_id}: title_el must be a non-empty string")
        if not isinstance(domain_id, str) or not domain_id:
            raise ValueError(f"{module_id}: domain_id must be a non-empty string")
        if type(available) is not bool:
            raise ValueError(f"{module_id}: available must be true or false")
        if not isinstance(status, str) or not status:
            raise ValueError(f"{module_id}: status must be a non-empty string")
        if not isinstance(lesson, dict):
            raise ValueError(f"{module_id}: lesson must be a mapping")
        lesson_html = lesson.get("html")
        if lesson_html is not None and (
            not isinstance(lesson_html, str) or not lesson_html
        ):
            raise ValueError(f"{module_id}: lesson.html must be a string or null")
        module_projection.append(
            {
                "id": module_id,
                "order": order,
                "display_code": display_code,
                "title_el": title_el,
                "domain_id": domain_id,
                "available": available,
                "status": status,
                "lesson_html": lesson_html,
            }
        )

    domain_projection.sort(key=lambda item: (item["order"], item["id"]))
    module_projection.sort(key=lambda item: (item["order"], item["id"]))
    return {
        "version": version,
        "domains": domain_projection,
        "modules": module_projection,
    }


def render_curriculum_data(data: Any) -> str:
    """Return the deterministic JavaScript projection for parsed curriculum."""

    payload = _browser_payload(data)
    rendered_json = json.dumps(payload, ensure_ascii=False, indent=2)
    return f"{HEADER}window.NTT_CURRICULUM = {rendered_json};\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail instead of writing when assets/curriculum-data.js is stale",
    )
    args = parser.parse_args(argv)

    try:
        data = load(SOURCE)
        expected = render_curriculum_data(data)
    except (OSError, CurriculumYAMLError, ValueError) as exc:
        print(f"Curriculum data generation failed: {exc}", file=sys.stderr)
        return 1

    if args.check:
        try:
            current = OUTPUT.read_text(encoding="utf-8")
        except FileNotFoundError:
            current = None
        except (OSError, UnicodeDecodeError) as exc:
            print(f"Cannot read {OUTPUT.relative_to(ROOT)}: {exc}", file=sys.stderr)
            return 1
        if current != expected:
            print(
                "assets/curriculum-data.js is stale; run "
                "'python scripts/generate_curriculum_data.py'.",
                file=sys.stderr,
            )
            return 1
        print("Generated curriculum data is in sync.")
        return 0

    try:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        with OUTPUT.open("w", encoding="utf-8", newline="\n") as output_file:
            output_file.write(expected)
    except OSError as exc:
        print(f"Cannot write {OUTPUT.relative_to(ROOT)}: {exc}", file=sys.stderr)
        return 1

    print(f"Generated {OUTPUT.relative_to(ROOT)}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
